name: 'Github Team Mention Notifier'
description: 'Notifies communication platforms via webhooks when a team is mentioned in Github.'
author: 'C.M.P.Soares, Lda.'
branding:
  color: 'purple'
  icon: 'message-square'
inputs:
  config_path:
    description: 'Path to the configuration JSON file.'
    required: false
    default: 'notifications_config.json'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/cmpsoares/gh-team-mention-notifier:v1.0.15'
