name: Publish Docker image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
    tags:
      - 'v*'  # Trigger on tags like v1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: cmpsoares
        password: ${{ secrets.CR_PAT_ACTION_DOCKET_PUBLISH }}

    - name: Set up Docker image tag
      id: image_tag
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          IMAGE_TAG=${GITHUB_REF#refs/tags/}
        else
          IMAGE_TAG=latest
        fi
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/cmpsoares/gh-team-mention-notifier:${{ env.IMAGE_TAG }}
