name: Test Action

on: [push]

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Run the Action
          run: python src/notify_teams.py
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NOTIFICATIONS_CONFIG_PATH: 'test/config.json'  # Your test path
  