name: Team Mention Notification Test
on:
  push:
    branches:
      - main
  issue_comment:
    types: [created, edited]
  pull_request_review_comment:
    types: [submitted, edited]
  pull_request:
    types: [opened, reopened, assigned, edited, synchronize]
  issues:
    types: [opened, assigned, edited]

jobs:
  notification_job_trunk:
    runs-on: ubuntu-latest
    name: Notify when team mentioned (main branch)
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Notify Teams (from main)
      uses: cmpsoares/gh-team-mention-notifier@main
      env:
        TEST_FAKE_SECRET: ${{ secrets.TEST_FAKE_SECRET }}
        # Add more environment variables as needed

  notification_job_latest_release:
    runs-on: ubuntu-latest
    name: Notify when team mentioned (latest release)
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Notify Teams (from latest release)
      uses: cmpsoares/gh-team-mention-notifier@v1.0.3
      env:
        TEST_FAKE_SECRET: ${{ secrets.TEST_FAKE_SECRET }}
        # Add more environment variables as needed
