name: Team Mention Notification Test

on:
  issues:
    types: [opened, edited, reopened, assigned]
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review, review_requested]
  issue_comment:
    types: [created, edited]
  pull_request_review:
    types: [submitted, edited]
  pull_request_review_comment:
    types: [created, edited]
  workflow_run:
    workflows: [Publish Docker image]  # The name of your Docker workflow
    types:
      - completed

jobs:
  notification_job_trunk:
    runs-on: ubuntu-latest
    name: Notify when team mentioned (main branch)
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run container (from main branch code)
      uses: docker://ghcr.io/cmpsoares/gh-team-mention-notifier:latest
      with:
        config_path: './test/config.json'
      env:
        TEST_FAKE_SECRET: ${{ secrets.TEST_FAKE_SECRET }}
        # Add more environment variables as needed

  notification_job_latest_release:
    runs-on: ubuntu-latest
    name: Notify when team mentioned (latest release)
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run container (from latest release)
      uses: docker://ghcr.io/cmpsoares/gh-team-mention-notifier:v1.0.16
      with:
        config_path: './test/config.json'
      env:
        TEST_FAKE_SECRET: ${{ secrets.TEST_FAKE_SECRET }}
        # Add more environment variables as needed

  notification_job_latest_release_external:
    runs-on: ubuntu-latest
    name: Notify when team mentioned (latest release/Action call)
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run GitHub Action (from latest release)
      uses: cmpsoares/gh-team-mention-notifier@main
      with:
        config_path: './test/config.json'
      env:
        TEST_FAKE_SECRET: ${{ secrets.TEST_FAKE_SECRET }}
        # Add more environment variables as needed
  
  notification_job_latest_release_external_version:
    runs-on: ubuntu-latest
    name: Notify when team mentioned (Action call - version)
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run GitHub Action (from latest release)
      uses: cmpsoares/gh-team-mention-notifier@v1.0.16
      with:
        config_path: './test/config.json'
      env:
        TEST_FAKE_SECRET: ${{ secrets.TEST_FAKE_SECRET }}
        # Add more environment variables as needed
  