name: Team Mention Notification
on:
  push:
    branches:
      - main
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [submitted]
  pull_request:
    types: [opened, reopened, assigned]
  issues:
    types: [opened, assigned]

jobs:
  notification_job:
    runs-on: ubuntu-latest
    name: Notify when team mentioned
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Notify Teams
      uses: cmpsoares/gh-team-mention-notifier@v1.0.0
      env:
        TEST_FAKE_SECRET: ${{ secrets.TEST_FAKE_SECRET }}
        # Add more environment variables as needed